import vine from '@vinejs/vine'

const COUNTRY_CODES = [
  'AF',
  'AX',
  'AL',
  'DZ',
  'AS',
  'AD',
  'AO',
  'AI',
  'AQ',
  'AG',
  'AR',
  'AM',
  'AW',
  'AU',
  'AT',
  'AZ',
  'BS',
  'BH',
  'BD',
  'BB',
  'BY',
  'BE',
  'BZ',
  'BJ',
  'BM',
  'BT',
  'BO',
  'BQ',
  'BA',
  'BW',
  'BV',
  'BR',
  'IO',
  'BN',
  'BG',
  'BF',
  'BI',
  'KH',
  'CM',
  'CA',
  'CV',
  'KY',
  'CF',
  'TD',
  'CL',
  'CN',
  'CX',
  'CC',
  'CO',
  'KM',
  'CG',
  'CD',
  'CK',
  'CR',
  'CI',
  'HR',
  'CU',
  'CW',
  'CY',
  'CZ',
  'DK',
  'DJ',
  'DM',
  'DO',
  'EC',
  'EG',
  'SV',
  'GQ',
  'ER',
  'EE',
  'ET',
  'FK',
  'FO',
  'FJ',
  'FI',
  'FR',
  'GF',
  'PF',
  'TF',
  'GA',
  'GM',
  'GE',
  'DE',
  'GH',
  'GI',
  'GR',
  'GL',
  'GD',
  'GP',
  'GU',
  'GT',
  'GG',
  'GN',
  'GW',
  'GY',
  'HT',
  'HM',
  'VA',
  'HN',
  'HK',
  'HU',
  'IS',
  'IN',
  'ID',
  'IR',
  'IQ',
  'IE',
  'IM',
  'IL',
  'IT',
  'JM',
  'JP',
  'JE',
  'JO',
  'KZ',
  'KE',
  'KI',
  'KP',
  'KR',
  'KW',
  'KG',
  'LA',
  'LV',
  'LB',
  'LS',
  'LR',
  'LY',
  'LI',
  'LT',
  'LU',
  'MO',
  'MK',
  'MG',
  'MW',
  'MY',
  'MV',
  'ML',
  'MT',
  'MH',
  'MQ',
  'MR',
  'MU',
  'YT',
  'MX',
  'FM',
  'MD',
  'MC',
  'MN',
  'ME',
  'MS',
  'MA',
  'MZ',
  'MM',
  'NA',
  'NR',
  'NP',
  'NL',
  'NC',
  'NZ',
  'NI',
  'NE',
  'NG',
  'NU',
  'NF',
  'MP',
  'NO',
  'OM',
  'PK',
  'PW',
  'PS',
  'PA',
  'PG',
  'PY',
  'PE',
  'PH',
  'PN',
  'PL',
  'PT',
  'PR',
  'QA',
  'RE',
  'RO',
  'RU',
  'RW',
  'BL',
  'SH',
  'KN',
  'LC',
  'MF',
  'PM',
  'VC',
  'WS',
  'SM',
  'ST',
  'SA',
  'SN',
  'RS',
  'SC',
  'SL',
  'SG',
  'SX',
  'SK',
  'SI',
  'SB',
  'SO',
  'ZA',
  'GS',
  'SS',
  'ES',
  'LK',
  'SD',
  'SR',
  'SJ',
  'SZ',
  'SE',
  'CH',
  'SY',
  'TW',
  'TJ',
  'TZ',
  'TH',
  'TL',
  'TG',
  'TK',
  'TO',
  'TT',
  'TN',
  'TR',
  'TM',
  'TC',
  'TV',
  'UG',
  'UA',
  'AE',
  'GB',
  'UM',
  'US',
  'UY',
  'UZ',
  'VU',
  'VE',
  'VN',
  'VG',
  'VI',
  'WF',
  'EH',
  'YE',
  'ZM',
  'ZW',
] as const

export const createIndividualSubscriptionValidator = vine.compile(
  vine.object({
    plan_type: vine.enum(['monthly', 'quarterly', 'annual']),
    product_id: vine.string().trim(),
    quantity: vine.number().min(1),
    customer: vine.object({
      email: vine.string().trim().email(),
      name: vine.string().trim().optional(),
      phone_number: vine.string().trim().optional(),
    }),
    billing: vine.object({
      street: vine.string().trim().minLength(1).maxLength(255),
      city: vine.string().trim().minLength(1).maxLength(100),
      state: vine.string().trim().minLength(1).maxLength(100),
      zipcode: vine.string().trim().minLength(1).maxLength(20),
      country: vine.enum(COUNTRY_CODES),
    }),
    metadata: vine.record(vine.any()).optional(),
    return_url: vine.string().trim().url().optional(),
    payment_link: vine.boolean().optional(),
    trial_period_days: vine.number().min(0).optional(),
  })
)

export const changeIndividualPlanValidator = vine.compile(
  vine.object({
    new_plan_type: vine.enum(['monthly', 'quarterly', 'annual']),
    new_product_id: vine.string().trim(),
    quantity: vine.number().min(1),
    proration_billing_mode: vine.literal('prorated_immediately'),
  })
)

export const createGroupSubscriptionValidator = vine.compile(
  vine.object({
    plan_type: vine.enum(['monthly', 'quarterly', 'annual']),
    product_id: vine.string().trim(),
    quantity: vine.number().min(1).max(100),
    customer: vine.object({
      email: vine.string().trim().email(),
      name: vine.string().trim().optional(),
      phone_number: vine.string().trim().optional(),
    }),
    billing: vine.object({
      street: vine.string().trim().minLength(1).maxLength(255),
      city: vine.string().trim().minLength(1).maxLength(100),
      state: vine.string().trim().minLength(1).maxLength(100),
      zipcode: vine.string().trim().minLength(1).maxLength(20),
      country: vine.enum(COUNTRY_CODES),
    }),
    metadata: vine.record(vine.any()).optional(),
    addons: vine
      .array(
        vine.object({
          addon_id: vine.string().trim(),
          quantity: vine.number().min(1),
        })
      )
      .optional(),
    return_url: vine.string().trim().url().optional(),
    payment_link: vine.boolean().optional(),
    trial_period_days: vine.number().min(0).optional(),
  })
)

export const joinGroupValidator = vine.compile(
  vine.object({
    invite_code: vine
      .string()
      .trim()
      .regex(
        /^[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{4}-[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{4}-[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{4}$/
      ),
  })
)

export const removeMemberValidator = vine.compile(
  vine.object({
    user_id_to_remove: vine.number().positive(),
    group_subscription_id: vine.number().positive(),
  })
)

export const changeSeatsValidator = vine.compile(
  vine.object({
    group_subscription_id: vine.number().positive(),
    new_product_id: vine.string().trim(),
    quantity: vine.number().min(1).max(100),
    proration_billing_mode: vine.literal('prorated_immediately'),
    addons: vine
      .array(
        vine.object({
          addon_id: vine.string().trim(),
          quantity: vine.number().min(1),
        })
      )
      .optional(),
  })
)

export const regenerateInviteCodeValidator = vine.compile(
  vine.object({
    group_subscription_id: vine.number().positive(),
  })
)
